//
//  NetworkUtil.h
//  MobiStream
//
//  Created by netris on 26.01.15.
//  Copyright (c) 2015 netris. All rights reserved.
//

#import <Foundation/Foundation.h>


#define CONNECTION_STATUS_UNDEFINED 0

#define CONNECTION_STATUS_CONNECTING_TO_PNP 1
#define CONNECTION_STATUS_CONNECTED_TO_PNP 2
#define CONNECTION_STATUS_DISCONNECTED_FROM_PNP 3

#define CONNECTION_STATUS_REGISTERING_CAMERA 4
#define CONNECTION_STATUS_REGISTERED_CAMERA 5
#define CONNECTION_STATUS_NOT_REGISTERED_CAMERA 6
#define CONNECTION_STATUS_RECEIVE_REGISTER_CAMERA 7

#define CONNECTION_STATUS_SEND_GET_ACTIONS 8
#define CONNECTION_STATUS_RECEIVE_GET_ACTIONS 9

#define CONNECTION_STATUS_OPENING_VIDEO_STREAM 10
#define CONNECTION_STATUS_OPENED_VIDEO_STREAM 11
#define CONNECTION_STATUS_DISCONNECTED_FROM_VIDEO_STREAM 12

#define CONNECTION_STATUS_CONNECTED 13
#define CONNECTION_STATUS_DISCONNECTED 14
#define CONNECTION_STATUS_CONNECTING 15
#define CONNECTION_STATUS_RECONNECTING 16

@interface NetworkUtil : NSObject

+ (NSString*) getIPAddress;

@end
